name: openjmu_lite
description: A lite version of OpenJMU for essential function.

version: 0.3.0+18

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: 1.1.1
  cached_network_image: 2.2.0+1
  connectivity: ^0.4.6+2
  cookie_jar: 1.0.1
  crypto: any
  device_info: ^0.4.1+4
  dio: 3.0.9
  dio_cookie_manager: 1.0.0
  event_bus: 1.1.1
  extended_image: 0.8.0
  extended_tabs: ^0.2.3
  fluttertoast: ^4.0.1
  flutter_cache_manager: ^1.1.3
  flutter_inappwebview: 3.2.0
  flutter_local_notifications: 1.4.3
  flutter_qr_reader: ^1.0.3
  flutter_screenutil: ^1.0.2
  flutter_spinkit: 4.1.2+1
  flutter_svg: ">=0.17.4 <2.0.0"
  flutter_webview_plugin: ^0.3.10
  hive: 1.4.1+1
  hive_flutter: ^0.3.0+1
  notification_permissions: ^0.4.3
  oktoast: 2.3.2
  open_file: 3.0.1
  package_info: ^0.4.0+13
  path_provider: 1.6.9
  permission_handler: 5.0.0+hotfix.6
  provider: 4.1.2
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
  uuid: ^2.0.4

dev_dependencies:
  build_runner: ^1.10.0
  ff_annotation_route: ^3.1.2
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0

dependency_overrides:
  crypto: 2.1.5
  dartx: 0.4.1
  image: 2.1.13
  intl: ^0.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/appCenter/
    - images/
  fonts:
    - family: chocolate
      fonts:
        - asset: assets/fonts/chocolate.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf