// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'openjmu-lite://about',
  'openjmu-lite://inappbrowser',
  'openjmu-lite://login-page',
  'openjmu-lite://main-page',
  'openjmu-lite://scan-qrcode',
  'openjmu-lite://settings-page'
];

class Routes {
  const Routes._();

  /// 关于页
  ///
  /// [name] : openjmu-lite://about
  ///
  /// [routeName] : 关于页
  static const String openjmuLiteAbout = 'openjmu-lite://about';

  /// 网页浏览
  ///
  /// [name] : openjmu-lite://inappbrowser
  ///
  /// [routeName] : 网页浏览
  ///
  /// [arguments] : [url, title, app, withCookie, withAppBar, withAction, withScaffold, keepAlive]
  static const String openjmuLiteInappbrowser = 'openjmu-lite://inappbrowser';

  /// 登录页
  ///
  /// [name] : openjmu-lite://login-page
  ///
  /// [routeName] : 登录页
  static const String openjmuLiteLoginPage = 'openjmu-lite://login-page';

  /// 首页
  ///
  /// [name] : openjmu-lite://main-page
  ///
  /// [routeName] : 首页
  static const String openjmuLiteMainPage = 'openjmu-lite://main-page';

  /// 扫描二维码
  ///
  /// [name] : openjmu-lite://scan-qrcode
  ///
  /// [routeName] : 扫描二维码
  static const String openjmuLiteScanQrcode = 'openjmu-lite://scan-qrcode';

  /// 设置页
  ///
  /// [name] : openjmu-lite://settings-page
  ///
  /// [routeName] : 设置页
  static const String openjmuLiteSettingsPage = 'openjmu-lite://settings-page';
}
